# Generated by Django 4.0.5 on 2022-07-07 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_createcurrency_vouchermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyAlter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slno', models.CharField(max_length=225)),
                ('currencys', models.CharField(max_length=225)),
                ('stdrate', models.CharField(max_length=225)),
                ('lastvrate', models.CharField(max_length=225)),
                ('specirate', models.CharField(max_length=225)),
                ('lastvrate2', models.CharField(max_length=225)),
                ('specirate2', models.CharField(max_length=225)),
                ('cname', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.createcurrency')),
            ],
        ),
        migrations.CreateModel(
            name='VoucherModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_name', models.CharField(max_length=225)),
                ('alias', models.CharField(max_length=225)),
                ('voucher_type', models.CharField(max_length=225)),
                ('abbreviation', models.CharField(max_length=225)),
                ('active_this_voucher_type', models.CharField(max_length=225)),
                ('method_voucher_numbering', models.CharField(max_length=225)),
                ('use_adv_conf', models.CharField(blank=True, max_length=225)),
                ('prvnt_duplictes', models.CharField(blank=True, default='Null', max_length=225)),
                ('use_effective_date', models.CharField(default='Null', max_length=225)),
                ('allow_zero_value_trns', models.CharField(max_length=225)),
                ('allow_naration_in_voucher', models.CharField(max_length=225)),
                ('make_optional', models.CharField(max_length=225)),
                ('provide_naration', models.CharField(max_length=225)),
                ('print_voucher', models.CharField(max_length=225)),
            ],
        ),
        migrations.DeleteModel(
            name='VoucherModel',
        ),
    ]
