# Generated by Django 4.0.5 on 2022-07-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_currencyalter_vouchermodels_delete_vouchermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmodel',
            name='does_it_affect',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AddField(
            model_name='groupmodel',
            name='nature_of_group',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='alias',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='gp_behaves_like_sub_ledger',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='method_to_allocate_usd_purchase',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='name',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='nett_debit_credit_bal_reporting',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='under',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='used_for_calculation',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
    ]
