# Generated by Django 4.0.5 on 2022-07-14 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_grp_alter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='grp_alter',
            new_name='GrpAlter',
        ),
    ]
